name: starfish_im
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
    sdk: '>=3.4.0 <4.0.0'
    flutter: ">=1.17.0"

dependencies:
    flutter:
        sdk: flutter
    starfish_utils:
        path: ../starfish_utils
    tencent_cloud_chat_uikit: 2.7.1
    tencent_calls_uikit: 2.5.0
    tencent_cloud_chat_push: 8.1.6906
    tencent_im_base: 8.0.0
    tencent_cloud_chat_vote_plugin: 1.2.0
    tencent_cloud_chat_customer_service_plugin: 0.1.0
    tencent_cloud_av_chat_room: 0.1.0
    extended_image: 8.2.4

dependency_overrides:
    http: ^1.0.0
    fc_native_video_thumbnail: ^0.9.0
    # 权限申请
    permission_handler: ^11.3.1
dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.0

flutter:
