spring.application.name=starfish_server
server.port=9900

mybatis.mapper-locations=classpath:/mapper/**/*.xml
mybatis.type-aliases-package=com.zoe.starfish_server.mybatis
logging.level.com.example.mybatis.mapper=debug

#Local
#spring.profiles.active=dev
#Prod
spring.profiles.active=prod

